version: "3.8"

services:
  es01:
    image: elasticsearch:7.16.1
    # build: .
    container_name: es01
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      # - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elastic-data:/usr/share/elasticsearch/data
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
