version: "3.8"

services:
  grafana:
    image: grafana/grafana-enterprise:8.3.3
    # build: .
    container_name: grafana
    volumes:
      - ./grafana-data:/var/lib/grafana
    ports:
      - 3000:3000
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
