version: "3.8"

services:
  app:
    build: .
    container_name: go_app
    # entrypoint: .docker/entrypoint.sh
    volumes:
      - .:/go/src/
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
