version: "3.8"

services:
  app:
    build: .
    container_name: nextjs_app
    entrypoint: ./.docker/entrypoint.sh
    ports:
      - 3001:3000
    volumes:
      - .:/home/node/app
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
