apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: herculesr/ifsfc5-backend:latest
          envFrom:
            - secretRef:
                name: backend
          ports:
            - containerPort: 3000
          # resources:
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
